### ISSUE TITLE
モーダルの上にモーダルを表示したい

### ISSUE THREAD

**Issue by kfukuoka** [ktsn/vue-thin-modal#11]
とても素晴らしい機能性で便利に使わせていただいております。

一点ご相談があるのですが、良いモーダル機能を探しておりブログで以下の文章を拝見させていただいたいのですが、現在modal.pushをすると以前のモーダルが消えるようになっているのですがどのようにすればいいのかわからず、ご相談させていただければと思います。

> モーダルの表示はスタックで管理していて、モーダルの上にモーダルとかもやろうと思えばできる (UI 的にどうなんだというのは置いといて)。

イメージとしてはfull-sizeのモーダルの上にdialogのモーダルを表示したいと考えております。
例）レスポンシブ（スマホを前提）：リスト選択（全画面モーダル）→Yes/Noなどの確認モーダル（ダイアログ）

**Comment by ktsn** [comment]
見た目的にモーダルの上に他のモーダルを表示したいということならサポートするつもりはないです。理由は以下の通りです。

- モーダルは現在のユーザの操作を止め、強制的かつ一時的に特定のことがらに注目させたり操作を求めるものなので、それが頻繁に発生する UI はあまり良いものだとは思えません。
- ↑の用途以外にモーダルを使っているのならばページ遷移などに変えるほうが history も残るし、複雑性も下がって良いと思っています。
- モーダル一つ表示するだけでも、使い勝手を良くするにはそれなりに複雑な実装をする必要があり、それを任意の数かぶせれるようにするのは困難です。

`modal.push` は表示上は一つのモーダルしかでませんが、内部ではスタックで積まれていて、一つ前のモーダルに戻ることができるようになっているので、どうしてもモーダルで実装したいのであれば機能面はそれで問題ないはずです。

モーダルの上に別のモーダルがあるという見た目が重要であるならば、vue-thin-modal のコンテンツ内に v-show などで別のダイアログを置くのがいいんじゃないかと思います。

**Comment by kfukuoka** [comment]
丁寧なご説明＆ご回答ありがとうございます！

御指南いただいた内容で今一度、仕様に関して考えてみたいと思います。
