### ISSUE TITLE
<modal-portal> is already created error with Nuxt

### ISSUE THREAD

**Issue by remarks** [ktsn/vue-thin-modal#15]
Hi, I'm able to replicate this [bug](#12) in a different scenario.

1. `autoMountPortal` is set to false
2. `<modal-portal />` is defined in both `@/layouts/layout-1.vue` and `@layouts/layout-2.vue`

If I'm paging from one layout to the other, it tries to destroy the first portal and re-create the second as shown in this screenshot.

![image](https://user-images.githubusercontent.com/1432193/47608541-261ce980-d9e4-11e8-9901-4d5731ba52a1.png)

**Comment by ktsn** [comment]
This is because `modal-portal` is meant to only placed as global / shared component in `App.vue`, for example. But I see the use case in the Nuxt.js which needs to placed on different layouts. I'm reconsider the assertion to let work in Nuxt.js.

Thanks for reporting this!

**Comment by ktsn** [comment]
fixed on v1.1.4
