### ISSUE TITLE
In Nuxt modal content loses scope

### ISSUE THREAD

**Issue by sebmor** [ktsn/vue-thin-modal#16]
For example I am required to do `this.$nuxt.$store.$dispatch` instead of `this.$store.$dispatch` for content that resides in `<modal>`

This is a problem when I have a component inside `<modal>` that is also used elsewhere outside the modal.

**Comment by ktsn** [comment]
Do you mount portal component manually? https://github.com/ktsn/vue-thin-modal#manually-mount-portal
When you want to inherit some context from root instance, you need to mount it in that way.

If it's not the case, providing a reproduction with some example github repository may help us to solve it.

**Comment by sebmor** [comment]
I found that indeed I can circumvent it by importing the `<portal-modal>` manually. But this solution fails when dealing with multiple layouts in Nuxt. Which is in any real app pretty much guaranteed. The <portal-modal> will get destroyed when changing layout and it will throw an error.

It would be great if somehow <portal-modal> would support Nuxt layouts or that we somehow retain the context. Packages like https://github.com/LinusBorg/portal-vue retain the context so it should be possible?

**Comment by ktsn** [comment]
It's tracked on #15 and I'll work on it tonight. Let's close this issue then 🙂

**Comment by sebmor** [comment]
@ktsn Are you still planning to incorporate this?

**Comment by ktsn** [comment]
I already fixed the error on v1.1.4.

**Comment by sebmor** [comment]
You are awesome, thanks!
