### ISSUE TITLE
disable-backdrop doesn't work

### ISSUE THREAD

**Issue by tic40** [ktsn/vue-thin-modal#20]
Hi, It's a nice library! I appreciate your great work.

Anyway, I encounter a bug that `disable-backdrop` doesn't work on the latest version v1.2.0. (i've confirmed it works well on v1.1.4)

This change(https://github.com/ktsn/vue-thin-modal/commit/93fcd79) seems to cause the bug.
thanks :)

**Comment by ktsn** [comment]
Thank you for filing this issue. This has been fixed in v1.2.1
