### ISSUE TITLE
Listening to close event

### ISSUE THREAD

**Issue by ko-yelie** [ktsn/vue-thin-modal#5]
I want to listen to close event so that I can execute arbitrary processing when I close the modal.
Like this.
```html
<modal name="example" @close="onClose">
</modal>
```
```js
new Vue({
  el: '.example',
  methods: {
    onClose () {
    }
  }
})
```
I would be pleased if you could consider adding features.
Thank you.

**Comment by ktsn** [comment]
@ko-yelie 
I've introduced `before-open` / `opened` / `before-close` / `closed` event on `<Modal>` component. You can try it on v1.0.0.

https://github.com/ktsn/vue-thin-modal#events

**Comment by ko-yelie** [comment]
I was able to listen to close event. Thank you! 😄
